services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/production.db

    # =====================================================
    # DEVELOPMENT MODE CONFIGURATION
    # Uncomment these lines for development mode
    # =====================================================
    volumes:
      - .:/app
      - /app/node_modules  # Don't override node_modules
      - /app/.next  # Don't override .next directory
    command: npm run dev  # Run in development mode

    # =====================================================
    # PRODUCTION MODE CONFIGURATION
    # Uncomment these lines for production mode and comment out the development section above
    # =====================================================
    # volumes:
    #   - ./src:/app/src  # Only mount source code
    #   - ./public:/app/public  # For public assets
    #   - ./prisma:/app/prisma  # For database files
    # Command is not needed here as it will use the default from Dockerfile (npm start)
