// Import the Task type
import { Task } from '@/app/types';
import { getLockedReportingPeriodAction } from '@/app/tasks/actions';

/**
 * @deprecated Use getLockedReportingPeriodAction instead
 * This function is kept for backward compatibility but simply forwards to getLockedReportingPeriodAction
 */
export async function getCurrentReportingPeriod(): Promise<{ periodStart: Date; periodEnd: Date }> {
  return getLockedReportingPeriodAction();
}

/**
 * Adds a specified number of days to a date
 */
export function addDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
} 

/**
 * Groups tasks by their type
 * @param tasks Array of Task objects
 * @returns Dictionary where keys are task types and values are arrays of tasks with that type
 */
export function groupTasksByType(tasks: Task[]): Record<string, Task[]> {
  return tasks.reduce((acc, task) => {
    const typeName = task.type.name;
    if (!acc[typeName]) {
      acc[typeName] = [];
    }
    acc[typeName].push(task);
    return acc;
  }, {} as Record<string, Task[]>);
} 

/**
 * Extracts plain text from an HTML report generated by generateReportHTML
 * @param html The HTML report string
 * @returns A clean, prompt-friendly list of tasks
 */
export function extractPlainTextFromReport(html: string): string {
  // Handle empty HTML report
  if (!html || html.trim() === '') {
    return '';
  }
  
  // Remove HTML tags and decode HTML entities
  const text = html
    .replace(/<h[2-3]>(.*?)<\/h[2-3]>/g, '\n$1\n') // Convert headers to newlines
    .replace(/<a href=".*?">#<\/a>/g, '') // Remove link tags
    .replace(/<li>(.*?)<\/li>/g, '• $1\n') // Convert list items to bullet points
    .replace(/<ul>|<\/ul>/g, '') // Remove ul tags
    .replace(/&nbsp;/g, ' ') // Replace &nbsp; with spaces
    .trim();

  // Clean up multiple newlines and spaces
  return text
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .join('\n');
} 